
services:
  nginx:
    image: nginx:latest
    container_name: my-nginx-container
    ports:
      - "8080:80" # Beispiel-Port
    volumes:
      # Stellt sicher, dass diese Zeile genau so aussieht
      - ./nginx.conf:/etc/nginx/nginx.conf